# Generated by Django 2.2.27 on 2022-03-11 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='raw_reading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eye_value', models.DecimalField(decimal_places=7, max_digits=10)),
                ('engagement_value1', models.DecimalField(decimal_places=7, max_digits=10)),
                ('engagement_value2', models.DecimalField(decimal_places=7, max_digits=10)),
                ('engagement_value3', models.DecimalField(decimal_places=7, max_digits=10)),
                ('engagement_value4', models.DecimalField(decimal_places=7, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('engagement', models.BooleanField(default=False)),
                ('instructor', models.CharField(max_length=200)),
                ('eye_weight', models.DecimalField(decimal_places=7, max_digits=10)),
                ('engagement_weight1', models.DecimalField(decimal_places=7, max_digits=10)),
                ('engagement_weight2', models.DecimalField(decimal_places=7, max_digits=10)),
                ('engagement_weight3', models.DecimalField(decimal_places=7, max_digits=10)),
                ('engagement_weight4', models.DecimalField(decimal_places=7, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='event_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(max_length=600)),
                ('students', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sever.student')),
            ],
        ),
    ]
